### ISSUE TITLE
NASAPower Error

### ISSUE THREAD

**Issue by Mohgli** [ajwdewit/pcse#21] opened 2016-11-10 09:52 UTC
Hi

Thank you for the great model and detailed tutorial. When going through the tutorial I fail when trying to access NASAPower data although the NASA seems to work properly. There seems to be an issue with the nasapower.py script. That is what I get as error.

 wdp = NASAPowerWeatherDataProvider(latitude=10, longitude=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mohgli\Anaconda3\envs\py2_pcse\lib\site-packages\pcse\db\nasapower.py", line 105, in __init__
    self._get_and_process_NASAPower(self.latitude, self.longitude)
  File "C:\Users\Mlohgli\Anaconda3\envs\py2_pcse\lib\site-packages\pcse\db\nasapower.py", line 144, in _get_and_process_NASAPower
    self.description = self._parse_header(powerdata)
  File "C:\Users\Mohgli\Anaconda3\envs\py2_pcse\lib\site-packages\pcse\db\nasapower.py", line 323, in _parse_header
    header.append(powerdata[20])
IndexError: list index out of range

Apreciate your help on this. Thanks

**Comment by ajwdewit** [comment] 2016-11-12 19:16
Dear Mohgli,

Thanks for the error report, I can reproduce your problem.
I will have a look at this, maybe the NASA power site changed its return 
data format or this is a bug in my code

regards,

Allard

**Comment by ajwdewit** [comment] 2016-11-13 12:11
Dear Mohgli,

the problem should be fixed now. It was caused by the NASA POWER website having moved to https:// while I was querying with http://

If you pip install from the master branch on my github repo, you should get the latest version (it is not on PyPI yet.)

regards,

Allard

**Closed by ajwdewit** 2016-11-13 12:11 UTC

**Comment by Mohgli** [comment] 2016-11-14 12:57
Thank you Allard for the fast turnaround. Works fine now. Kind regards, Mohgli

**Comment by henriquefl24** [comment] 2021-09-22 12:27
Hello,

I'm having some problems retrieving data from NASA power and I just don't know how to solve it. I'll leave what I'm trying to do and the error report:

from pcse.db.nasapower import NASAPowerWeatherDataProvider
weather = NASAPowerWeatherDataProvider(latitude=-21.24, longitude=-48.28, force_update=False, ETmodel='PM')
-------------------------------------------------------------------------------------------------------------------------------------------
PCSEError: Failed retrieving POWER data, server returned HTTP code: 422 on following URL https://power.larc.nasa.gov/cgi-bin/v1/DataAccess.py?request=execute&identifier=SinglePoint&parameters=ALLSKY_TOA_SW_DWN%2CALLSKY_SFC_SW_DWN%2CT2M%2CT2M_MIN%2CT2M_MAX%2CT2MDEW%2CWS2M%2CPRECTOT&lat=-21.24&lon=-48.28&startDate=19830701&endDate=20210922&userCommunity=AG&tempAverage=DAILY&outputList=JSON&user=anonymous
---------------------------------------------------------------------------
PCSEError                                 Traceback (most recent call last)
<ipython-input-15-e418a23db6ba> in <module>
      1 from pcse.db.nasapower import NASAPowerWeatherDataProvider
----> 2 weather = NASAPowerWeatherDataProvider(latitude=-21.24, longitude=-48.28, force_update=False, ETmodel='PM')

~\.conda\envs\py3_pcse\lib\site-packages\pcse\db\nasapower.py in __init__(self, latitude, longitude, force_update, ETmodel)
     96             self.logger.debug(msg)
     97             # No cache file, we really have to get the data from the NASA server
---> 98             self._get_and_process_NASAPower(self.latitude, self.longitude)
     99             return
    100 

~\.conda\envs\py3_pcse\lib\site-packages\pcse\db\nasapower.py in _get_and_process_NASAPower(self, latitude, longitude)
    132         """Handles the retrieval and processing of the NASA Power data
    133         """
--> 134         powerdata = self._query_NASAPower_server(latitude, longitude)
    135         if not powerdata:
    136             msg = "Failure retrieving POWER data from server. This can be a connection problem with " \

~\.conda\envs\py3_pcse\lib\site-packages\pcse\db\nasapower.py in _query_NASAPower_server(self, latitude, longitude)
    230             msg = ("Failed retrieving POWER data, server returned HTTP " +
    231                    "code: %i on following URL %s") % (req.status_code, req.url)
--> 232             raise PCSEError(msg)
    233 
    234         msg = "Successfully retrieved data from NASA Power"

PCSEError: Failed retrieving POWER data, server returned HTTP code: 422 on following URL https://power.larc.nasa.gov/cgi-bin/v1/DataAccess.py?request=execute&identifier=SinglePoint&parameters=ALLSKY_TOA_SW_DWN%2CALLSKY_SFC_SW_DWN%2CT2M%2CT2M_MIN%2CT2M_MAX%2CT2MDEW%2CWS2M%2CPRECTOT&lat=-21.24&lon=-48.28&startDate=19830701&endDate=20210922&userCommunity=AG&tempAverage=DAILY&outputList=JSON&user=anonymous
